#pragma once

using namespace ATL;

template <class T>
class CProxy_ITestEvents : public IConnectionPointImpl<T, &__uuidof( _ITestEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
